# Generated by Django 5.2.3 on 2025-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('fullstack', 'fullstack'), ('backend', 'backend'), ('frontend', 'frontend'), ('mobile', 'mobile'), ('scraping', 'scraping'), ('bots', 'bots'), ('data-analysis', 'data-analysis'), ('cybersecurity', 'cybersecurity')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url_github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
