# Generated by Django 5.2.3 on 2025-07-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_category_project_url_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
